POST http://localhost:3002/api/persons HTTP/1.1
Content-Type: application/json

{
"name": "xxxdfffffdd",
"number": "454dfffffdd"
}

###

GET http://localhost:3002/api/persons HTTP/1.1

###

GET http://localhost:3002/api/info HTTP/1.1

###

GET http://localhost:3002/api/persons/1 HTTP/1.1

###

DELETE http://localhost:3002/api/persons/5 HTTP/1.1
